dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.5.0
dotenv: .env
networks:
  default: development
limits:
  gas_limit_deploy: 
    min: 2
    max: 1000000000
  gas_limit_tx: 
    min: 1
    max: 1000000000